# Generated by Django 5.1.4 on 2025-01-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_applicationlog_alter_attachment_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationlog',
            name='level',
        ),
        migrations.AddField(
            model_name='applicationlog',
            name='interacted_by',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='NEW', max_length=15),
        ),
    ]
